language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
notifications:
  recipients:
    - carlos@plataformatec.com.br
    - jose.valim@plataformatec.com.br
    - rafael.franca@plataformatec.com.br
    - rodrigo.flores@plataformatec.com.br