language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - Gemfile
matrix:
  allow_failures:
    - rvm: 2.2
      gemfile: gemfiles/Gemfile.rails-3.2.x
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: gIz2OQRVwzQBFJYVuc4D9rZ6w+9Mk8sTtGHy56qUvJSQI6c3st3eNXs7xpDlJ2DJ0x/4P4BltzYemvILghQGfk2drjMNKBc9Fxx7Wk1jnVzeLp2zt3Q2kp2kBf/uChfyXLKOsiBOKBG8SGe8dIf8N7wWPSKgUK9zHdH8M71A7kw=
